language: ruby
sudo: required

services:
  - docker

script: 'true'

after_success: 
  - docker build -t rushildayabme/meetapp-client ./web/frontend
  - docker build -t rushildayabme/meetapp-api ./api
  - docker build -t rushildayabme/meetapp-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rushildayabme/meetapp-client
  - docker push rushildayabme/meetapp-api
  - docker push rushildayabme/meetapp-nginx

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: meetAPP
  env: Meetapp-env
  bucket_name: elasticbeanstalk-us-west-2-720830066180
  bucket_path: meetAPP
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY